name: action Hello World

on:
  push:
    branches:
      - test

jobs:
  hello-world:
    runs-on: ubuntu-18.04
    steps:
      - name: Step Hola Mundo
        run: |
          echo "Hola Victor"
      - name: Dime la fecha
        run: date
      - run: ls -l
