name: Deployment Pipeline

on:
  push:
    branches:
      - "test"
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: test
        run: npm test
