name: Release node
on:
  push:
    branches:
      - "master"
env:
  GH_TOKEN: ${{ secrets.TOKEN }}
  NPM_TOKEN: ${{ secrets.TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
jobs:
  release:
    # if: "!contains(github.event.commits[0].message, 'Initial commit')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install npm v8.11.0
        run: npm install -g npm@v8.11.0
      - name: Install dependencies
        run: npm install
      - name: Release
        run: npx semantic-release
